apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: app-javb
  template:
    metadata:
      labels:
        app: app-java
    spec:
      containers:
       - name: java-app
         image: 
         ports:
           - containerPort: 8080

